copyright = "© Vandan Parmar"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en-gb"
timeZone = "Europe/London"
timeout = "120s"

baseURL = "https://vandanpv.co.uk/" # Replace with your GitHub Pages URL
title = "Vandan P-V's Portfolio" # Replace with your name or site title
theme = "hugo-theme-gallery"

[build]
  publishResources = false

[imaging]
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    includeFields = "ImageDescription|Orientation|DateTimeOriginal|Exposure|Date|FocalLength|ApertureValue|ExposureTime|ISO|Date|Make|Model|Aperture|FNumber"

[params]
  # Optional: Add a description for your site
  description = "A portfolio of my photography work."

  # Add parameters specific to the hugo-theme-gallery
  [params.gallery]
  # The theme is highly configurable. Refer to the theme's documentation for all options:
  # https://github.com//hugo-theme-gallery#configuration
  # Below are some common options:

  # Set the base URL for images (usually the same as baseURL)
  baseURL = "https://vandanpv.co.uk/" # Ensure this matches your site URL

  # Configure how albums are displayed on the homepage
  albumsPerRow = 3 # Number of albums per row on the index page
  maxAlbums = 0 # Maximum number of albums to display (0 for all)

  # Configure how photos are displayed within an album
  photosPerRow = 4 # Number of photos per row within an album
  maxPhotos = 0 # Maximum number of photos per album (0 for all)

  # Enable PhotoSwipe for lightbox effect
  enablePhotoSwipe = true

  # Set the title for the album index page (the homepage)
  albumIndexTitle = "Welcome to Vandan's photography portfolio"

  
  [params.socialIcons]
    instagram = "https://www.instagram.com/vandan.p_v/"
  
  [params.author]
    name = "Vandan Parmar-Venkat"

# You can add more configurations here based on the theme's documentation